### ISSUE TITLE
change password exception

### ISSUE THREAD

**Issue by herestomwiththeweather** [bace/oscurrency#14]
it seems that a login_reset_key_expire attribute was added to Person for the purpose of password reset (d9657a247c8613319ae42436cedaf2ae338f2ae5) but code that uses it (Person#check_login_key) is also called from change_password? when someone tries to change their password:

 [RAILS_ROOT]/.bundle/gems/ruby/1.8/gems/activesupport-2.3.11/lib/active_support/whiny_nil.rb:52:in `method_missing'
 [RAILS_ROOT]/app/models/person.rb:512:in`check_login_key'
 [RAILS_ROOT]/app/models/person.rb:518:in `change_password?'
 [RAILS_ROOT]/app/controllers/people_controller.rb:170:in`update'

**Comment by herestomwiththeweather** [comment]
resolved.
